### ISSUE TITLE
Add backend selection to CLI

### ISSUE THREAD

**Issue by RMeli** [RMeli/spyrmsd#108]
PR #107 added functionality to select a backend (graph library). The CLI could also benefit from this functionality: a user should be able to select the backend as a CLI argument.

**Comment by Jnelen** [comment]
Hi, I'm willing to take this one on!

My plan is to add an argument (-b or --backend), which will parsed using _validate_backend function we've defined in graph.
After that we can set the backend and run the rest like normal. My one question would we if we can test this using pytest? Ofcourse i'll run some (trivial) local tests, but not sure if we can "properly" integrate it in pytest? One way I could maybe see it work is using subprocess, but maybe there are better ways?

**Comment by RMeli** [comment]
> Hi, I'm willing to take this one on!

I just opened #112, which includes this. 😬 Sorry about that.

I was about to tag you there, asking if you would be available to review the PR. Your insight would be very helpful!

> My one question would we if we can test this using `pytest`?

No, currently the CLI is not tested properly.

**Comment by Jnelen** [comment]
> > Hi, I'm willing to take this one on!
> 
> I just opened #112, which includes this. 😬 Sorry about that.

Great that you did it already!
> I was about to tag you there, asking if you would be available to review the PR. Your insight would be very helpful!

For sure, i'll have a quick look!
> > My one question would we if we can test this using `pytest`?
> 
> No, currently the CLI is not tested properly.

Yeah I guess we also only (want to) output the actual RMSD, which on it's own doesn't really indicate the backend.. Not sure if there is a proper way to test this. But I suppose that it completely relies on the set_backend feature, and if that works that feature _should_ work aswell?

**Comment by RMeli** [comment]
> Yeah I guess we also only (want to) output the actual RMSD, which on it's own doesn't really indicate the backend.. Not sure if there is a proper way to test this.

I added print statements when testing. =) Definitely a sloppy test...
