### ISSUE TITLE
Error message: name 'load' is not defined

### ISSUE THREAD

**Issue by 1980whisky** [RMeli/spyrmsd#79]
Hello,

I am using spyrmsd to compute the RMSD between two mol2 structures. The installation was carried out as instructed. When I type: `python3 -m spyrmsd -h`, the help message appears as it is supposed to, so I think there's no problem till this point.

However, when I type the command line to compare two mol2 files as follows: `python3 -m spyrmsd xxx.mol2 yyy.mol2`, an error message appears: 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "~ /anaconda3/envs/spyrmsd-env/lib/python3.11/site-packages/spyrmsd/__main__.py", line 31, in <module>
    ref = io.loadmol(args.reference)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~ /anaconda3/envs/spyrmsd-env/lib/python3.11/site-packages/spyrmsd/io.py", line 65, in loadmol
    mol = load(fname)
          ^^^^
NameError: name 'load' is not defined. Did you mean: 'float'?
```

The job is not done. Could you please verify this problem? Thank you in advance.

Regards,

**Comment by RMeli** [comment]
PR #81 will add a proper error message if neither RDKit nor OpenBabel are found.

**Comment by 1980whisky** [comment]
Thank you for your response. The problem has been fixed.

**Comment by RMeli** [comment]
No problem @1980whisky, I'm glad it's solved.
